Домашняя работа #2
htmlacademy-javascript/1750255-keksobooking-23 pull request #2
Opened 2021-06-01 14:03 UTC by RomanValdaev

2021-06-01 14:45 UTC, VAnastasia requested changes

2021-06-01 14:45 UTC, VAnastasia commented on js/main.js
> +    integer = Math.floor(Math.random() * (max - min + 1)) + min; //Максимум и минимум включаются.
Переменную integer надо объявить через const

2021-06-01 14:45 UTC, VAnastasia commented on js/main.js
> +    console.log(integer);
Выводы в консоль замени на return

2021-06-01 14:45 UTC, VAnastasia commented on js/main.js
> +    console.log(floatInt.toFixed(2));
Также надо заменить вывод в консоль на return. И еще подумать, как преобразовать floatInt.toFixed(2) в число, так как сейчас это строка

2021-06-01 14:45 UTC, VAnastasia commented on js/main.js
> +  }
Перед коммитом очень желательно запускать линтер, для этого надо в консоли выполнить команду npm install, а перед каждым коммитом npm test и исправить все ошибки

2021-06-02 03:51 UTC, RomanValdaev commented on js/main.js
> +    integer = Math.floor(Math.random() * (max - min + 1)) + min; //Максимум и минимум включаются.
Да, действительно не объявил переменную.
Глупая ошибка.
А как так тогда работал код?

2021-06-02 03:51 UTC, RomanValdaev commented on js/main.js
> +    console.log(integer);
Замена в цикле If {...} проведена.

2021-06-02 03:57 UTC, RomanValdaev commented on js/main.js
> +    console.log(floatInt.toFixed(2));
Замена на return в цикле If {...} проведена.
По вопросу floatInt.toFixed(2) в число. Да, мне известно что получается строка. Подозревал что тут будут проблемы.
Но я опустил данный момент, так как в ТЗ не было четкого определения по данному получаемому типу переменной. 
При отладке в консоли и определении типа получаемого результата в переменной, данная переменная отображается как number.
Поскольку надо получить число, то предлагаю самый простой вариант - перевести ее в число с помощью Number/
Да , это добавит объем кода, но лучше на старте отработать работу на простых вещах, а потом двигаться к более сложным.

2021-06-02 03:57 UTC, RomanValdaev commented on js/main.js
> +  }
Да, действительно это так.
Я его отключил так как он форматировал код по своему, а потом просто забыл проверить.
Спасибо за комментарии.

2021-06-02 14:47 UTC, merged