Домашнее задание №4
htmlacademy-javascript/1750255-keksobooking-23 pull request #3
Opened 2021-06-08 07:16 UTC by RomanValdaev

Высылаю на проверку домашнее задание №4.

2021-06-08 09:48 UTC, VAnastasia requested changes

2021-06-08 09:48 UTC, VAnastasia commented on js/main.js
> +const numberOfArrays = 10;
По критерию Б7 все константы (постоянные значения) пишутся заглавными буквами, например, USER_NUMBER_MIN

2021-06-08 09:48 UTC, VAnastasia commented on js/main.js
> +    const floatIntNumber = Number(floatInt.toFixed(4));//приводим полученное строковое значение к типу Number.
Вроде число знаков после запятой вынесли в параметр?

2021-06-08 09:48 UTC, VAnastasia commented on js/main.js
> +    avatar:'img/avatars/user0' + getRandomIntInclusive(userNumberMin, userNumberMax) + '.png',
Ошибки. на которые ругается eslint желательно исправлять перед каждым коммитом. Тут он жалуется, что вместо конкатенации строк надо использовать шаблонные строки, вот так:
avatar: `img/avatars/user0${getRandomIntInclusive(userNumberMin, userNumberMax)}.png`

2021-06-08 09:48 UTC, VAnastasia commented on js/main.js
> +    features: getArrayRandomElement(hotelFeatures),
features - должно быть массивом. Для простоты можно воспользоваться методом slice, примерно так: 
features; hotelFeatures.slice(0, getRandomIntInclusive(1, hotelFeatures.length))

2021-06-08 09:48 UTC, VAnastasia commented on js/main.js
> +    photos: getArrayRandomElement(realEstatePhoto),
photos - это тоже массив

2021-06-08 09:48 UTC, VAnastasia commented on js/main.js
> +    lng: getFloatInt(latitudeValueMin, latitudeValueMax),
так как координаты используются в двух местах, лучше записать их в переменные и подставить здесь и в offer.title

2021-06-08 09:48 UTC, VAnastasia commented on js/main.js
> +const currentObjectName = {
здесь лучше сделать функцию, которая будет возвращать объект объявления, вот так
function getOffer() {
  return {
    author: {
      avatar: ....
    },
    ...
  }
}

2021-06-08 09:48 UTC, VAnastasia commented on js/main.js
> +}
Чтобы создать массив объявлений, можно воспользоваться примером из демки https://up.htmlacademy.ru/javascript/23/demos/5345#15
Вот так:
const similarOffers = new Array(SIMILAR_OFFER_COUNT).fill(null).map(() => createOffer())
где SIMILAR_OFFER_COUNT = 10. а createOffer - это функция, возвращающая объект объявления

2021-06-09 01:54 UTC, RomanValdaev commented on js/main.js
> +const numberOfArrays = 10;
Исправлено в соответствии с замечаниями.

2021-06-09 02:44 UTC, RomanValdaev commented on js/main.js
> +    features: getArrayRandomElement(hotelFeatures),
Исправлено в соответствии с замечаниями.

2021-06-09 02:44 UTC, RomanValdaev commented on js/main.js
> +    photos: getArrayRandomElement(realEstatePhoto),
Исправлено в соответствии с замечаниями.

2021-06-09 03:56 UTC, RomanValdaev commented on js/main.js
> +    photos: getArrayRandomElement(realEstatePhoto),
Исправлено в соответствии с замечаниями.

2021-06-09 03:56 UTC, RomanValdaev commented on js/main.js
> +    lng: getFloatInt(latitudeValueMin, latitudeValueMax),
Исправлено в соответствии с замечаниями.

2021-06-09 03:56 UTC, RomanValdaev commented on js/main.js
> +const currentObjectName = {
Исправлено в соответствии с предложениями.

2021-06-09 03:57 UTC, RomanValdaev commented on js/main.js
> +}
Исправлено в соответствии с предложениями. Действительно, решение лежит на поверхности.

2021-06-09 04:07 UTC, RomanValdaev commented on js/main.js
> +}
Исправлено в соответствии с замечаниями.

2021-06-09 06:11 UTC, VAnastasia requested changes

2021-06-09 06:11 UTC, VAnastasia commented on js/main.js
> +const LATITUDE_MIDDLE_VALUE = getFloatInt(LATITUDE_VALUE_MIN, LATITUDE_VALUE_MAX, COORDS_ACCURACY);
Если перенести эти 2 строчки внутрь функции createOffer перед return, координаты в каждом объекте будут уникальными. В следующих заданиях, по этим координатам будем добавлять на карту метки, и если у них будут одинаковые координаты, они будут друг над другом, что не есть хорошо

2021-06-09 06:11 UTC, VAnastasia commented on js/main.js
> +      adress: `Координаты места расположения: ${LONGITUDE_MIDDLE_VALUE}, ${LATITUDE_MIDDLE_VALUE}`,
adress надо на address заменить, потому что в дальнейшем с сервера будут приходить данные именно с таким полем

2021-06-09 07:00 UTC, merged