Правда или действие (часть 1)
htmlacademy-javascript/1750255-keksobooking-23 pull request #7
Opened 2021-06-26 07:50 UTC by RomanValdaev

Анастасия!
Прошу проверить мое очередное творение!

2021-06-26 14:20 UTC, VAnastasia requested changes

2021-06-26 14:20 UTC, VAnastasia commented on js/form-validation.js
> +  const MIN_NIGHT_PRICE = 1;
минимальная цена 0

2021-06-26 14:20 UTC, VAnastasia commented on js/form-validation.js
> +    guestsSelect.setCustomValidity(message);
забыл
roomsSelect.reportValidity();
guestsSelect.reportValidity();

2021-06-26 14:20 UTC, VAnastasia commented on js/form-validation.js
> +    const guestOfNumbers = guestsSelect.value;
value в инпутах всегда строка. надо в ROOMS и GUEST записать строки '1', '2' и т.д.

2021-06-26 14:20 UTC, VAnastasia commented on js/form-validation.js
> +export {formValidation};
сейчас форма может отправиться с неверными данными. проверка должна работать и на событие submit формы

2021-06-27 13:39 UTC, RomanValdaev commented on index.html
> +          <input id="address" name="address" type="number" readonly>
+

2021-06-27 13:39 UTC, RomanValdaev commented on js/form-validation.js
> +  const MIN_NIGHT_PRICE = 1;
++

2021-06-27 13:40 UTC, RomanValdaev commented on js/form-validation.js
> +    guestsSelect.setCustomValidity(message);
++

2021-06-27 14:08 UTC, RomanValdaev commented on js/form-validation.js
> +export {formValidation};
поменял 'change' на 'submit'

2021-06-27 14:20 UTC, RomanValdaev commented on js/form-validation.js
> +    const guestOfNumbers = guestsSelect.value;
Исправил в соответствии с замечанием:

 const ROOMS = {
    one: '1',
    two: '2',
    three: '2',
    hundred: '100',
  };
  const GUEST = {
    one: '1',
    two: '2',
    three: '3',
    norooms: 'не для гостей',
  };

2021-06-27 14:39 UTC, merged