Правда или действие (часть 2)
htmlacademy-javascript/1750255-keksobooking-23 pull request #9
Opened 2021-07-01 03:05 UTC by RomanValdaev

Добрый день, Анастасия!

Прошу принять на проверку ДЗ "Правда или действие (часть 2)".
Все ДЗ сформировал в отдельном файле form-booking.js.
Пока сделал так.
Если надо будет объединить код с файлом по обработке формы (как указано в ТЗ), то сделаю.

Спасибо!

2021-07-01 03:33 UTC, VAnastasia requested changes

2021-07-01 03:33 UTC, VAnastasia commented on js/form-booking.js
> +  function timeIntСhange() {
все функции сделай стрелочными (критерий Д5)
timeIntСhange и timeOutСhange сделай одной функцией с 2-мя параметрами и вынеси ее из formTimeChange

2021-07-01 03:33 UTC, VAnastasia commented on js/form-booking.js
> +  const PALACE_MIN_COST = 10000;
константы выносим в начало модуля
здесь удобно использовать объект-словарь, его создаем до функции
{
bungalow: BUNGALO_MIN_COST,
flat: FLAT_MIN_COST,
...
}
тогда можно отказаться от громоздкой конструкции ниже switch ... case

2021-07-01 03:33 UTC, VAnastasia commented on js/form-booking.js
> +        houseCurrentPrice.setAttribute('min', BUNGALO_MIN_COST);
обрати внимание, в других местах ты записываешь атрибуты напрямую
houseCurrentPrice.min = BUNGALO_MIN_COST
использование нескольких вариантов не пройдет по критерию Д7

2021-07-02 08:44 UTC, RomanValdaev commented on js/form-booking.js
> +  const PALACE_MIN_COST = 10000;
Переменные вынес в начало модуля.

2021-07-02 08:45 UTC, RomanValdaev commented on js/form-booking.js
> +  function timeIntСhange() {
Исправлено под пошаговым руководством Наставника!

2021-07-02 08:46 UTC, RomanValdaev commented on js/form-booking.js
> +  const PALACE_MIN_COST = 10000;
От конструкции "switch ... case" пока отказываться не буду, так как надо браться за следующую домашку.

2021-07-02 09:08 UTC, RomanValdaev commented on js/form-booking.js
> +        houseCurrentPrice.setAttribute('min', BUNGALO_MIN_COST);
Исправлено в соответствии с замечаниями.

2021-07-02 09:39 UTC, merged